name: there will be bread
markdown: kramdown


# Setup
title:               there are only two mantras, yum and yuck. mine is yum.
description:         a cure for creative constipation
url:                 http://www.cindygao.com
paginate:            5
paginate_path:       "/blog/page:num/"
gems:		     [jekyll-paginate, jekyll-gist]
